version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: studyflow_db
    environment:
      POSTGRES_USER: studyflow
      POSTGRES_PASSWORD: studyflow_pass
      POSTGRES_DB: studyflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U studyflow"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
